# Generated by Django 5.0.7 on 2024-07-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_client_product_alter_todo_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estacao",
            fields=[
                ("id_estacao", models.AutoField(primary_key=True, serialize=False)),
                ("codigo_estacao", models.IntegerField()),
                ("placa_estacao", models.CharField(max_length=8)),
                ("estacao", models.CharField(max_length=30)),
                ("status_estacao", models.CharField(max_length=30)),
                ("data_criacao_estacao", models.DateTimeField(auto_now_add=True)),
                ("data_validade_orcamento_estacao", models.DateField()),
            ],
            options={
                "db_table": "estacao",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id_material", models.AutoField(primary_key=True, serialize=False)),
                ("codigo_material", models.IntegerField()),
                ("placa_material", models.CharField(max_length=8)),
                (
                    "produto_material",
                    models.CharField(default="DESMONTA", max_length=30),
                ),
                ("quantidade_material", models.IntegerField(default=1)),
                ("data_criacao_material", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "material",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("codigo_produto", models.AutoField(primary_key=True, serialize=False)),
                ("linha_servico_produto", models.CharField(max_length=50)),
                ("tipo_produto", models.CharField(max_length=50)),
                (
                    "preco_custo_produto",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "preco_venda_produto",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("data_cadastro_produto", models.DateTimeField(auto_now_add=True)),
                ("data_ultima_atualizacao", models.DateField(auto_now=True)),
            ],
            options={
                "db_table": "produto",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                ("codigo_veiculo", models.AutoField(primary_key=True, serialize=False)),
                ("placa_veiculo", models.CharField(max_length=8)),
                ("marca_veiculo", models.CharField(max_length=30)),
                ("modelo_veiculo", models.CharField(max_length=30)),
                ("ano_veiculo", models.CharField(max_length=30)),
                ("cor_veiculo", models.CharField(max_length=30)),
                ("proprietario_veiculo", models.CharField(max_length=100)),
                (
                    "cpf_proprietario_veiculo",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "telefone_proprietario_veiculo",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                ("data_veiculo", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "veiculo",
                "managed": False,
            },
        ),
    ]
